services:
  nginx:
    image: nginx:alpine
    networks:
      default:
        aliases:
          - example.local
    ports:
      - 80:80
      - 443:443
    volumes:
      - project:/project
      - ./nginx/servers:/etc/nginx/conf.d
      - ./nginx/base.conf:/etc/nginx/base.conf
      - ./nginx/server.conf:/etc/nginx/server.conf
      - ./nginx/php5.conf:/etc/nginx/php5.conf
      - ./nginx/php7.conf:/etc/nginx/php7.conf
      - ./nginx/php8.0.conf:/etc/nginx/php8.0.conf
      - ./nginx/php8.2.conf:/etc/nginx/php8.2.conf
      - ./nginx/node18.conf:/etc/nginx/node18.conf
      - ./nginx/server.key:/etc/ssl/server.key
      - ./nginx/server.crt:/etc/ssl/server.crt

volumes:
  project:
    external: true
