version: '3.4'

services:
  nginx:
    image: nginx:alpine
    links:
      - mysql
      - php
    ports:
      - 80:80
      - 443:443
    volumes:
      - $HOST_ROOT/Desktop:/desktop
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/server.conf:/etc/nginx/server.conf
      - ./nginx/ssl.conf:/etc/nginx/ssl.conf
      - ./nginx/php.conf:/etc/nginx/php.conf
      - ./nginx/mime.types:/etc/nginx/mime.types
      - ./nginx/server.crt:/etc/nginx/server.crt
      - ./nginx/server.key:/etc/nginx/server.key

  mysql:
    image: mysql
    volumes:
      - ./mysql/custom.cnf:/etc/mysql/conf.d/custom.cnf
    environment:
      - MYSQL_ROOT_PASSWORD=mysql

  pgsql:
    image: postgres
    environment:
      - POSTGRES_USER=pgsql
      - POSTGRES_PASSWORD=pgsql

  redis:
    image: redis:alpine

  php:
    build: ./php
    image: php-fpm
    volumes:
      - $HOST_ROOT/Desktop:/desktop
      - ./php/php.ini:/usr/local/etc/php/php.ini
