version: '3.4'

services:
  nginx:
    image: nginx:alpine
    links:
      - mysql
      - php
    ports:
      - 10000:10000
      - 20000:20000
    volumes:
      - $HOST_ROOT/Desktop:/desktop
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl.conf:/etc/nginx/ssl.conf
      - ./nginx/php.conf:/etc/nginx/php.conf
      - ./nginx/server.crt:/etc/nginx/server.crt
      - ./nginx/server.key:/etc/nginx/server.key

  mysql:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=mysql

  pgsql:
    image: postgres
    environment:
      - POSTGRES_USER=pgsql
      - POSTGRES_PASSWORD=pgsql

  php:
    build: ./php
    image: php-fpm
    volumes:
      - $HOST_ROOT/Desktop:/desktop
      - ./php/php.ini:/usr/local/etc/php/php.ini
