version: '3.4'

x-php-common: &php-common
  volumes:
    - project:/project
    - ./php/php.ini:/usr/local/etc/php/php.ini
services:
  nginx:
    image: nginx:alpine
    links: ['mysql', 'sqlserver', 'redis', 'php5', 'php7', 'php8', 'php8.2']
    networks:
      default:
        aliases:
          - example.local
    ports:
      - 80:80
      - 443:443
    volumes:
      - project:/project
      - ./nginx/servers:/etc/nginx/conf.d
      - ./nginx/base.conf:/etc/nginx/base.conf
      - ./nginx/server.conf:/etc/nginx/server.conf
      - ./nginx/php7.conf:/etc/nginx/php7.conf
      - ./nginx/php8.conf:/etc/nginx/php8.conf
      - ./nginx/php8.2.conf:/etc/nginx/php8.2.conf
      - ./nginx/php5.conf:/etc/nginx/php5.conf
      - ./nginx/server.key:/etc/ssl/server.key
      - ./nginx/server.crt:/etc/ssl/server.crt

  mysql:
    image: mysql
    volumes:
      - ./mysql/custom.cnf:/etc/mysql/conf.d/custom.cnf
      - ./mysql/initdb:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=mysql

  pgsql:
    image: postgres
    environment:
      - POSTGRES_USER=pgsql
      - POSTGRES_PASSWORD=pgsql

  sqlserver:
    image: mcr.microsoft.com/mssql/server
    ports:
      - 1433:1433
    environment:
      - SA_PASSWORD=Pass0001
      - ACCEPT_EULA=Y

  redis:
    image: redis:alpine

  php7:
    build:
      context: ./php
      dockerfile: ./v7/Dockerfile
    image: php7
    command: ["unitd", "--no-daemon", "--control", "0.0.0.0:9876"]
    <<: *php-common

  php8:
    build:
      context: ./php
      dockerfile: ./v8/Dockerfile
    image: php8
    command: ["unitd", "--no-daemon", "--control", "0.0.0.0:9876"]
    <<: *php-common

  php8.2:
    build:
      context: ./php
      dockerfile: ./v8.2/Dockerfile
    image: php8.2
    command: ["unitd", "--no-daemon", "--control", "0.0.0.0:9876"]
    <<: *php-common

  php5:
    build:
      context: ./php
      dockerfile: ./v5/Dockerfile
    image: php5-fpm
    <<: *php-common

volumes:
  project:
    external: true
