version: '3.4'

services:
  proxy:
    image: jwilder/nginx-proxy
    links: ['nginx']
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./proxy/server.crt:/etc/nginx/certs/server.crt
      - ./proxy/server.key:/etc/nginx/certs/server.key

  nginx:
    image: nginx:alpine
    links: ['mysql', 'php']
    volumes:
      - $HOST_ROOT/Desktop:/desktop
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/server.conf:/etc/nginx/server.conf
      - ./nginx/ssl.conf:/etc/nginx/ssl.conf
      - ./nginx/php.conf:/etc/nginx/php.conf
      - ./nginx/mime.types:/etc/nginx/mime.types
    environment:
      - VIRTUAL_HOST=*.{{DOMAIN}}
      - CERT_NAME=server

  mysql:
    image: mysql
    volumes:
      - ./mysql/custom.cnf:/etc/mysql/conf.d/custom.cnf
    environment:
      - MYSQL_ROOT_PASSWORD=mysql

  pgsql:
    image: postgres
    environment:
      - POSTGRES_USER=pgsql
      - POSTGRES_PASSWORD=pgsql

  redis:
    image: redis:alpine

  php:
    build: ./php
    image: php-fpm
    volumes:
      - $HOST_ROOT/Desktop:/desktop
      - ./php/php.ini:/usr/local/etc/php/php.ini
