version: '3.4'

services:
  nginx:
    image: nginx:alpine
    links: ['mysql', 'php']
    ports:
      - 80:80
    volumes:
      - project:/project
      - ./nginx/server.conf:/etc/nginx/server.conf
      - ./nginx/php.conf:/etc/nginx/php.conf
      - ./nginx/servers:/etc/nginx/conf.d

  mysql:
    image: mysql
    volumes:
      - ./mysql/custom.cnf:/etc/mysql/conf.d/custom.cnf
    environment:
      - MYSQL_ROOT_PASSWORD=mysql

  pgsql:
    image: postgres
    environment:
      - POSTGRES_USER=pgsql
      - POSTGRES_PASSWORD=pgsql

  redis:
    image: redis:alpine

  php:
    build: ./php
    image: php-fpm
    volumes:
      - project:/project
      - ./php/php.ini:/usr/local/etc/php/php.ini

volumes:
  project:
    external: true
