FROM php:5-fpm

ADD scripts /scripts

RUN bash /scripts/bcmath
RUN bash /scripts/exif
RUN bash /scripts/mcrypt
RUN bash /scripts/pdo_dblib
RUN bash /scripts/redis
RUN bash /scripts/xdebug
RUN bash /scripts/zip
