#!/bin/bash

apt-get update
apt-get install -y --no-install-recommends unixodbc-dev gnupg2
curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add -
curl https://packages.microsoft.com/config/debian/10/prod.list > /etc/apt/sources.list.d/mssql-release.list
apt-get update
ACCEPT_EULA=Y apt-get install -y --no-install-recommends msodbcsql17 mssql-tools
pecl install pdo_sqlsrv
docker-php-ext-enable pdo_sqlsrv
