#!/bin/sh

if [ $(echo $PHP_VERSION | grep '^5') ]
then
    pecl install xdebug-2.5.5
elif [ $(echo $PHP_VERSION | grep '^7') ]
then
    pecl install xdebug-3.1.6
else
    pecl install xdebug
fi

docker-php-ext-enable xdebug
