FROM php:8.0-fpm

ADD scripts /scripts

RUN bash /scripts/apcu
RUN bash /scripts/bcmath
RUN bash /scripts/exif
RUN bash /scripts/ldap
RUN bash /scripts/opcache
RUN bash /scripts/pdo_mysql
RUN bash /scripts/pdo_pgsql
RUN bash /scripts/pdo_sqlsrv
RUN bash /scripts/redis
RUN bash /scripts/xdebug
RUN bash /scripts/zip
